### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by nalves599** [Dman95/SASM#152] opened 2021-01-18 12:30 UTC
Create a translation to portuguese.

**Comment by alglus** [comment] 2021-01-22 23:25
Duplicate of #150

**Comment by emendblu** [comment] 2021-01-22 23:59
I don’t need a Portuguese translation right now. Can you send over the original please and I will use my Portuguese-English dictionary to translate if needed.

**Comment by votemikejones** [comment] 2021-01-23 01:41
I  need the Portuguese version tonight or we’re going to lose A OT of money $$$$$$$



What’s our eta?

**Comment by emendblu** [comment] 2021-01-23 02:23
How much money are we talking? I got a guy standing by, he don’t speak the language but I have faith he can get it done

**Comment by nalves599** [comment] 2021-01-23 11:13
I have the translation already done. I can create a pull request.

**Closed** 2021-01-24 11:16 UTC

**Comment by GuruShankar** [comment] 2021-01-24 16:17
HI .. I am not sure y I am receiving these emails.. ? please unsubscribe me

**Comment by emendblu** [comment] 2021-01-24 16:25
Don’t be modest. You are an important part of this team and deserve to get updates just as much as everyone else.
