### ISSUE TITLE
Debugger not working on Arch Linux

### ISSUE THREAD

**Issue by jakobkukla** [Dman95/SASM#151] opened 2020-11-18 20:33 UTC
Version: 3.11.1
Distro: Arch Linux

The debugger does not work at all in NASM (x86). GAS and FASM are working fine (also x86). I have similar symptoms to this issue #76 (except no crashing), which should be solved. I checked the linking options: They are correctly set to `-fno-pie -no-pie`.

**Comment by kerstinlieff** [comment] 2020-11-18 23:42
UNSUBSCRIBE ME PLEASE

**Comment by Schabolon** [comment] 2020-11-21 19:53
I am experiencing the same problem (Distro: Arch Linux; SASM-Version: 3.11.1)

**Comment by QBrunner** [comment] 2020-11-23 14:09
I can confirm the problem. Sasm-Version is also 3.11.1

**Comment by Dman95** [comment] 2021-02-07 19:15
I can't reproduce because I don't have Arch Linux. I'll be glad to accept pull request or comment about fixing the issue.

**Comment by twa022** [comment] 2021-02-10 19:54
I updated the AUR package to 3.12.0. Had the issue resolved or are people will experiencing this?
If still an issue, was it present before 3.11.1 or did it start presenting with that version?

**Comment by Dman95** [comment] 2021-02-13 15:19
Seems same issue as on Fedora 33. Should be fixed in version 3.12.1. 

To apply the fix update SASM and reset settings: Settings -> Common -> Reset all.

**Closed by Dman95** 2021-02-13 15:19 UTC
Labels: bug

**Comment by ahmed-mehanna** [comment] 2021-07-18 16:54
I was having the same issue, but I was using Pop Os

I tried to download Sasm 3.12.1 and this solved the issue for me. I hope it will solve it for you.

**Comment by ahmed-mehanna** [comment] 2021-07-18 16:55
> Version: 3.11.1
> Distro: Arch Linux
> 
> The debugger does not work at all in NASM (x86). GAS and FASM are working fine (also x86). I have similar symptoms to this issue #76 (except no crashing), which should be solved. I checked the linking options: They are correctly set to `-fno-pie -no-pie`.

**Comment by emendblu** [comment] 2021-07-18 18:12
We need this debugger to work ASAP!

**Comment by votemikejones** [comment] 2021-07-18 19:59
Fuck your ASAP

**Comment by emendblu** [comment] 2021-07-18 20:40
That is not helpful! We are loosing precious time here! Get your shit together team!

**Comment by mickeyslaven** [comment] 2021-07-19 05:00
PLEASE FOR THE LOVE OF CHRIST UNSUBSCRIBE ME FROM THIS EMAIL THREAD. This had been going on for years.

**Comment by emendblu** [comment] 2021-07-19 09:15
If you are on the email chain then you are part of our team! Now let’s get that debugger working!

**Comment by mickeyslaven** [comment] 2021-07-19 10:42
We were all clearly put here for a reason. I really doubt my email was added to this chair to fix the debugger. I think we were put here by god to continue Terry Davis’s work on gods holy temple. I will be quitting my job tonight to start polishing temple OS

**Comment by emendblu** [comment] 2021-07-19 11:05
You are a wise man
